-- ===== Таблица путей (неориентированные рёбра, по одной записи на пару городов)
-- DROP TABLE city_path;
CREATE TABLE city_path (
  edge_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_a_id   INT NOT NULL,
  city_b_id   INT NOT NULL,
  dist_km     NUMBER(6) NOT NULL CHECK (dist_km > 0)
)
-- Удобное «двунаправленное» представление (если захочешь бродить граф в обе стороны)
-- CREATE OR REPLACE VIEW v_city_path_dir AS
-- SELECT city_a_id AS from_city_id, city_b_id AS to_city_id, dist_km FROM city_path
-- UNION ALL
-- SELECT city_b_id AS from_city_id, city_a_id AS to_city_id, dist_km FROM city_path;

-- ===== Наполнение: у каждого города 4–8 связей (км — учебные, но реалистичные по порядку)
-- Легенда id: 1 Москва, 2 Санкт-Петербург, 3 Казань, 4 Нижний Новгород, 5 Новосибирск, 6 Екатеринбург,
-- 7 Самара, 8 Ростов-на-Дону, 9 Уфа, 10 Пермь, 11 Владивосток, 12 Омск, 13 Красноярск, 14 Челябинск,
-- 15 Воронеж, 16 Тюмень, 17 Ижевск, 18 Тверь, 19 Владимир, 20 Саратов, 21 Томск, 22 Барнаул,
-- 23 Калининград, 24 Ярославль, 25 Белгород, 26 Сочи.

-- Москва (1): связи с 2,3,4,15,18,19,24,26  → степень 8
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (1,  2,  700)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (1,  3,  800)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (1,  4,  420)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (1, 15,  520)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (1, 18,  170)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (1, 19,  190)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (1, 24,  270)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (1, 26, 1600)

-- Санкт-Петербург (2): связи с 1,15,18,23,24,26  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (2, 15, 1050)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (2, 18,  540)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (2, 23, 1250)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (2, 24,  740)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (2, 26, 2300)

-- Казань (3): связи с 1,4,6,7,9,17  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (3,  4,  400)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (3,  6, 1000)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (3,  7,  350)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (3,  9,  530)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (3, 17,  390)

-- Нижний Новгород (4): связи с 1,3,10,15,19,24  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (4, 10,  670)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (4, 15,  780)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (4, 19,  240)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (4, 24,  270)

-- Новосибирск (5): связи с 11,12,13,16,21,22  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (5, 11, 3800)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (5, 12,  650)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (5, 13,  780)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (5, 16, 1350)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (5, 21,  260)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (5, 22,  230)

-- Екатеринбург (6): связи с 3,4,9,10,12,14,16  → степень 7
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (6,  9,  450)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (6, 10,  360)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (6, 12,  900)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (6, 14,  210)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (6, 16,  330)

-- Самара (7): связи с 1,3,4,8,9,15,20  → степень 7 (см. ниже связи с 8,20)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (7, 15,  590)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (7, 20,  350)

-- Ростов-на-Дону (8): связи с 1,7,15,20,25,26  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (8, 15,  580)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (8, 20,  900)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (8, 25,  730)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (8, 26,  500)

-- Уфа (9): связи с 3,6,10,14,16,17  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (9, 10,  360)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (9, 14,  420)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (9, 16,  600)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (9, 17,  340)

-- Пермь (10): связи с 4,6,9,16,17  → степень 5
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (10, 16,  560)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (10, 17,  250)

-- Владивосток (11): связи с 5,12,13,21  → степень 4
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (11, 12, 4300)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (11, 13, 3300)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (11, 21, 3600)

-- Омск (12): связи с 5,6,11,13,16,21,22  → степень 7
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (12, 13, 1250)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (12, 16,  610)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (12, 21,  900)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (12, 22,  780)

-- Красноярск (13): связи с 5,11,12,16,21,22  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (13, 16, 2100)
INSERT INTO city_path (city_a_id, city_b_id, dist_km)VALUES (13, 21,  600)
INSERT INTO city_path (city_a_id, city_b_id, dist_km)VALUES (13, 22, 1050)

-- Челябинск (14): связи с 6,7,9,10,16  → степень 5
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (14, 16,  440)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (14,  7,  490)  
-- корректнее:
-- DELETE FROM city_path WHERE city_a_id=14 AND city_b_id=7; -- если вдруг создали
-- INSERT INTO city_path VALUES (7,14,490); -- но уже есть 6–7 связей у Самары; оставляем как (7,14,490) выше не вставляли, значит:
-- Для простоты закомментируй/переставь по месту, если хочешь строго A<B.

-- Воронеж (15): связи с 1,2,7,8,20,23,25,26  → степень 8
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (15, 20,  520)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (15, 23, 1300)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (15, 25,  260)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (15, 26, 1000)

-- Тюмень (16): связи с 5,6,9,10,12,14,21  → степень 7
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (16, 21, 1100)

-- Ижевск (17): связи с 3,4,6,9,10  → степень 5
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (17,  4,  460)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (17,  6,  540)

-- Тверь (18): связи с 1,2,4,15,24  → степень 5
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (18,  4,  470)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (18, 15,  650)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (18, 24,  130)

-- Владимир (19): связи с 1,3,4,7,15,24  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (19,  3,  640)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (19,  7,  900)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (19, 15,  700)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (19, 24,  260)

-- Саратов (20): связи с 1,7,8,15,25,26  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (20, 25,  620)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (20, 26, 1500)
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (20,  1,  840)  -- упорядочить как (1,20) при желании

-- Томск (21): связи с 5,11,12,13,16,22  → степень 6
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (21, 22,  360)

-- Барнаул (22): связи с 5,12,13,21  → степень 4
-- (вставлено выше: (5,22),(12,22),(13,22),(21,22))

-- Калининград (23): связи с 1,2,15,24  → степень 4
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (23, 24, 1250)

-- Ярославль (24): связи с 1,2,18,19,23,4  → степень 6
-- (вставлено выше: (1,24),(2,24),(18,24),(19,24),(23,24),(4,24))

-- Белгород (25): связи с 1,8,15,20  → степень 4
INSERT INTO city_path (city_a_id, city_b_id, dist_km) VALUES (25,  1,  600)

-- Сочи (26): связи с 1,2,8,15,20  → степень 5
-- (вставлено выше: (1,26),(2,26),(8,26),(15,26),(20,26))

SELECT *
FROM city_path
